baseURL = "https://samcalamos.com.au/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Sam Calamos"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Sam Calamos"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  description = "Landing Page"
  bio = "I work in the Clouds ‚òÅ"
  avatar = "images/BlueAlder_DP.png"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/BlueAlder"
    #instagram = "https://instagram.com/jdoe"
    twitter = "https://twitter.com/BlueAlder"
    linkedin = "https://linkedin.com/in/samuelcalamos"
    
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
    # 0 = { name = "ello", icon = "ello", style = "fab", link = "" } # empty links are relative to site root

    [params.contact.email]
      name = "email" # may be omitted. defaults to key name
      icon = "envelope" # may be omitted. defaults to key name
      style = "fas" # may be omitted. default = "fas"
      link = "mailto:sam.calamos@gmail.com"
    # [params.contact.linkedin]
    #   name = "linkedin"
    #   icon = "linkedin"
    #   style = "fas"
    #   link = "https://linkedin.com/in/samuelcalamos"
      
